### ISSUE TITLE
Source code isn't distributed with npm package

### ISSUE THREAD

**Issue by jamietre** [callmehiphop/pb-util#12]
The `build/index.js.map` file in the npm package points to source file `../index.ts` which isn't distributed.

**Comment by callmehiphop** [comment]
👋 @jamietre thanks for the bug report!

I guess map generation has changed since the last time I updated TypeScript 😢. I went ahead and published a patch release that will inline the ts source code into the map file. Seems to be working for me locally, but let me know if that's not the case for you!

**Comment by jamietre** [comment]
Works perfectly. Thanks for fixing this at lighting speed!

**Comment by callmehiphop** [comment]
Absolutely! Thanks again for reporting this 🥰
